import { Challenge } from '@/types/challenge';

export const challenges: Challenge[] = [
  {
    id: 'profile-card',
    title: '프로필 카드',
    day: 1,
    description: ' link를 포함한반응형 프로필 카드 UI를 구현합니다.',
    image: '/challenges/profile-card.png',
    isCompleted: false,
    difficulty: 'easy',
    path: '/challenges/profile-card',
  },
  {
    id: 'add-to-bag',
    title: '제품 상세페이지 (장바구니)',
    day: 2,
    description: '사이즈 선택 및 카트 기능이 있는 제품 상세 페이지 구현하기',
    image: '/challenges/add-to-bag.png',
    isCompleted: false,
    difficulty: 'medium',
    path: '/challenges/add-to-bag',
  },
  {
    id: 'mobile-navigation',
    title: '모바일 사이드 네비게이션',
    day: 3,
    description: '접근성 기능이 포함된 애니메이션 모바일 사이드 메뉴',
    image: '/challenges/mobile-navigation.png',
    isCompleted: false,
    difficulty: 'medium',
    path: '/challenges/mobile-navigation',
  },
  {
    id: 'contact-us',
    title: '문의하기',
    day: 4,
    description: '문의하기 UI',
    image: '/challenges/contact-us.png',
    isCompleted: false,
    difficulty: 'hard',
    path: '/challenges/contact-us',
  },
  {
    id: 'recipe',
    title: '레시피 UI',
    day: 5,
    description: 'Recipe Card UI',
    image: '/challenges/recipe.png',
    isCompleted: false,
    difficulty: 'easy',
    path: '/challenges/recipe',
  },
  {
    id: 'image-carousel',
    title: '캐러셀 UI',
    day: 6,
    description: '이미지 슬라이더',
    image: '/challenges/image-carousel.png',
    isCompleted: false,
    difficulty: 'hard',
    path: '/challenges/image-carousel',
  },
]; 