import { Revision } from '@/types/revision';

export const revisions: Revision[] = [
  // profile-card UI
  {
    id: 'wave-bg',
    title: '웨이브 애니메이션 배경 추가',
    description: '상단 이미지의 배경(purple, blue 그라데이션)에 웨이브 애니메이션 효과를 추가해주세요.',
    requestDate: '2024-02-15',
    status: 'completed',
    componentId: 'profile-card',
    path: '/challenges/profile-card/revisions/wave-bg',
  },
  {
    id: 'hover-effect',
    title: '소셜 링크 호버 효과 개선',
    description: '소셜 미디어 아이콘에 호버 시 팝업 효과와 툴팁을 추가해주세요.',
    requestDate: '2024-02-15',
    status: 'completed',
    componentId: 'profile-card',
    path: '/challenges/profile-card/revisions/hover-effect',
  },
  {
    id: 'dark-theme',
    title: '다크 테마 색상 개선',
    description: '다크 모드에서 프로필 카드의 배경과 텍스트 색상 대비를 더 개선해주세요.',
    requestDate: '2024-02-15',
    status: 'pending',
    componentId: 'profile-card',
    path: '/challenges/profile-card/revisions/dark-theme',
  },
  // product-detail UI
  {
    id: 'image-zoom',
    title: '제품 이미지 줌 기능 추가',
    description: '제품 이미지에 마우스 오버 시 확대 기능을 추가하고, 클릭 시 전체화면 모달로 볼 수 있게 해주세요.',
    requestDate: '2024-02-16',
    status: 'completed',
    componentId: 'product-detail',
    path: '/challenges/product-detail/revisions/image-zoom',
  },
  {
    id: 'size-guide',
    title: '사이즈 가이드 기능 추가',
    description: '사이즈 선택 영역 상단에 사이즈 가이드 버튼을 추가하고, 클릭 시 상세 치수 정보를 보여주는 모달을 표시해주세요.',
    requestDate: '2024-02-16',
    status: 'pending',
    componentId: 'product-detail',
    path: '/challenges/product-detail/revisions/size-guide',
  },
  {
    id: 'stock-indicator',
    title: '재고 상태 표시 개선',
    description: '각 사이즈별 재고 상태를 시각적으로 표시하고, 품절된 사이즈는 선택할 수 없도록 비활성화해주세요.',
    requestDate: '2024-02-16',
    status: 'pending',
    componentId: 'product-detail',
    path: '/challenges/product-detail/revisions/stock-indicator',
  },
  // side-navigation UI
  {
    id: 'swipe-gesture',
    title: '스와이프 제스처 지원',
    description: '모바일 환경에서 화면 가장자리에서의 스와이프로 네비게이션을 열고 닫을 수 있도록 제스처를 지원해주세요. 부드러운 스와이프 애니메이션도 함께 구현해주세요.',
    requestDate: '2024-02-16',
    status: 'pending',
    componentId: 'side-navigation',
    path: '/challenges/side-navigation/revisions/swipe-gesture',
  },
  {
    id: 'nested-menu',
    title: '중첩 메뉴 구조 지원',
    description: '메뉴 아이템에 서브메뉴를 추가하고, 확장/축소 애니메이션과 함께 계층적 네비게이션을 구현해주세요. 현재 메뉴의 깊이를 시각적으로 표현해주세요.',
    requestDate: '2024-02-16',
    status: 'pending',
    componentId: 'side-navigation',
    path: '/challenges/side-navigation/revisions/nested-menu',
  },
  {
    id: 'recent-menu',
    title: '최근 방문 메뉴 섹션',
    description: '사용자가 최근에 방문한 메뉴 항목을 별도 섹션으로 표시하고, 빠른 접근이 가능하도록 해주세요. 방문 시간도 함께 표시해주세요.',
    requestDate: '2024-02-16',
    status: 'pending',
    componentId: 'side-navigation',
    path: '/challenges/side-navigation/revisions/recent-menu',
  },
  {
    id: 'search-filter',
    title: '메뉴 검색 및 필터 기능',
    description: '많은 메뉴 항목을 빠르게 찾을 수 있도록 검색 기능을 추가하고, 카테고리별 필터링을 지원해주세요. 검색 결과는 실시간으로 표시해주세요.',
    requestDate: '2024-02-16',
    status: 'pending',
    componentId: 'side-navigation',
    path: '/challenges/side-navigation/revisions/search-filter',
  },
  {
    id: 'mini-variant',
    title: '미니 사이드바 모드',
    description: '사이드바를 아이콘만 표시하는 미니 모드로 전환할 수 있도록 해주세요. 호버 시 메뉴 레이블을 툴팁으로 표시하고, 필요한 경우 전체 메뉴로 쉽게 확장할 수 있게 해주세요.',
    requestDate: '2024-02-16',
    status: 'pending',
    componentId: 'side-navigation',
    path: '/challenges/side-navigation/revisions/mini-variant',
  },
  {
    id: 'context-menu',
    title: '메뉴 아이템 컨텍스트 메뉴',
    description: '각 메뉴 아이템에 우클릭 또는 길게 누르기로 활성화되는 컨텍스트 메뉴를 추가해주세요. 즐겨찾기 등록, 새 탭에서 열기, 링크 복사 등의 기능을 지원해주세요.',
    requestDate: '2024-02-16',
    status: 'pending',
    componentId: 'side-navigation',
    path: '/challenges/side-navigation/revisions/context-menu',
  },
]; 